<a href="https://colab.research.google.com/github/Ambar-Ghaffar/20SW019-SDA/blob/main/Lab_4_(20SW019).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Task#01
import numpy as np

A = np.arange(2, 34, 2).reshape(4, 4)

print(A)




[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [4]:
#Task#03
import numpy as np

# Create a 4x4 ndarray with columns filled using broadcasting
Y = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(Y)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [3]:
#task 2
A = np.arange(1, 26).reshape(5, 5)
print("A:")
print(A)

B = A[A % 2 != 0]
print("\nB (odd numbers from A):")
print(B)

A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

B (odd numbers from A):
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [7]:
#Task#04
from google.colab import drive
drive.mount('/NumPy.ipnyb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipnyb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[ 0.77226364  1.30456041 -0.83319617 ... -0.28630676  0.86792352
   0.66268826]
 [ 0.22149428 -0.92473293 -1.48688952 ... -0.25786325  0.30994213
  -0.40420551]
 [ 0.48212621 -0.55812271  1.66726645 ...  0.98046976 -0.09816532
   1.08890795]
 ...
 [-0.03773262 -0.65666644  0.10593186 ...  1.64438276 -1.5518722
  -1.48656152]
 [-1.58115133 -0.93920439 -0.52517313 ... -0.46598645 -0.49079283
  -1.57462899]
 [-0.13327424 -1.60006755 -1.22130521 ...  1.26074234  1.34217252
  -0.83244202]]
Average of all values in X_norm: 0.0
Average of minimum values in each column of X_norm: -1.7270271934735741
Average of maximum values in each column of X_norm: 1.7215980959346755
Random permutation of row indices: [839 614 783 770 303 878 173 437 853 725 107 948 347 939 861 126 280 167
 769 417 737 156  13 115 592 637 375 980  10 992 101 239 356 169 707 586
 969 452 916 340  88 864 368 882 287 857 669